#docker-comppose up -d
#docker-comppose down
version: "3.8"
services:
  db:
    container_name: mysqldb
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: tutorial
    ports:
      - 3306:3306
    networks:
      - masstransit-network  

  adminer:
    container_name: admmysql
    image: adminer
    restart: always
    ports:
      - 8080:8080

  rabbitmq:
    container_name: rabbitmq
    image: masstransit/rabbitmq    
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - 5672:5672
      - 15672:15672
    hostname: "rabbitmq"  
    networks:
      - masstransit-network

  app:
    container_name: masstransitapp
    image: masstransitapp
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__AMQPUrl=rabbitmq
      - ConnectionStrings__AMQPUser=guest
      - ConnectionStrings__AMQPPassword=guest
    ports:
      - 5000:5000
    networks:
      - masstransit-network

networks:
  masstransit-network:             